name: TEDxPitic
favicon: null
layout_spectrum: 0.3186606753151864
typography_spectrum: 0.24733799858950078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.44237337121739984
  lightness: 0.9550470465328544
  saturation: 0.3549391620326787
  rhythmicContrast: 0.735254101222381
purpose: []
